-name: "\U0001F41E Bug report"
description: Create a report to help us improve
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        **Before submitting a bug report**

        This repository is reserved for bug reports and block requests. If you have a usage question, you can:

        - Read the [documentation](https://www.tremor.so/docs/getting-started/installation)
        - Ask questions on [Slack](https://join.slack.com/t/tremor-community/shared_invite/zt-1u8jqmcmq-Fdr9B6MbnO7u8FkGh~2Ylg)

  - type: input
    id: url
    attributes:
      label: URL
      description: |
        Please insert the URL of the category or the specific Block
      placeholder: E.g. https://blocks.tremor.so/blocks/kpi-cards#kpi-card-1
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Block name
      description: |
        Please insert the Name/Title Block. If you want to report multiple Blocks, separate with a comma.
      placeholder: E.g. KPI Card with Chart
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: |
        What do we need to make the bug happen? Clear and concise description or instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
    validations:
      required: false
  - type: textarea
  attributes:
    label: Screenshots
    description: |
      You can attach images or files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Microsoft Edge
        - Safari
        - Firefox
        - Vivaldi
        - Brave
        - Other
  - type: dropdown
    id: device
    attributes:
      label: What device(s) are you seeing the problem on? (if applicable)
      multiple: true
      options:
        - Phone
        - Desktop
        - Tablet
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: Links? References? Anything that will give us more context about the issue you are encountering!
